#!/usr/bin/python3
import os
import py_compile

def compile_python_script(file_path):
        try:
                    py_compile.compile(file_path)
                            print(f"Compilation successful: {file_path} compiled to {file_path + 'c'}")
                                except py_compile.PyCompileError as e:
                                            print(f"Compilation failed: {e}")

                                            if __name__ == "__main__":
                                                    # Get the Python file name from the environment variable
                                                        pyfile = os.getenv('PYFILE')

                                                            if pyfile:
                                                                        compile_python_script(pyfile)
                                                                            else:
                                                                                        print("Environment variable PYFILE is not set.")

